version: '3.5'

services:
  unit-test:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew --no-daemon test"
    environment:
      - "USER=unittest"
    volumes:
      - "../../:/temporal-java-samples"

  fossa:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: /bin/sh
    environment:
      - BUILDKITE_BRANCH
      - FOSSA_API_KEY
    volumes:
      - "../../:/temporal-java-samples"
